/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingId = IDL.Nat;
export const Booking = IDL.Record({
  'id' : BookingId,
  'createdAt' : IDL.Int,
  'budget' : IDL.Nat,
  'location' : IDL.Text,
  'eventDate' : IDL.Text,
  'eventName' : IDL.Text,
});
export const BookingInput = IDL.Record({
  'budget' : IDL.Nat,
  'location' : IDL.Text,
  'eventDate' : IDL.Text,
  'eventName' : IDL.Text,
});
export const BookingResult = IDL.Variant({
  'ok' : BookingId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBookingById' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'submitBooking' : IDL.Func([BookingInput], [BookingResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingId = IDL.Nat;
  const Booking = IDL.Record({
    'id' : BookingId,
    'createdAt' : IDL.Int,
    'budget' : IDL.Nat,
    'location' : IDL.Text,
    'eventDate' : IDL.Text,
    'eventName' : IDL.Text,
  });
  const BookingInput = IDL.Record({
    'budget' : IDL.Nat,
    'location' : IDL.Text,
    'eventDate' : IDL.Text,
    'eventName' : IDL.Text,
  });
  const BookingResult = IDL.Variant({ 'ok' : BookingId, 'err' : IDL.Text });
  
  return IDL.Service({
    'getBookingById' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'submitBooking' : IDL.Func([BookingInput], [BookingResult], []),
  });
};

export const init = ({ IDL }) => { return []; };