/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'createdAt' : bigint,
  'budget' : bigint,
  'location' : string,
  'eventDate' : string,
  'eventName' : string,
}
export type BookingId = bigint;
export interface BookingInput {
  'budget' : bigint,
  'location' : string,
  'eventDate' : string,
  'eventName' : string,
}
export type BookingResult = { 'ok' : BookingId } |
  { 'err' : string };
export interface _SERVICE {
  'getBookingById' : ActorMethod<[BookingId], [] | [Booking]>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'submitBooking' : ActorMethod<[BookingInput], BookingResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];